### ISSUE TITLE
'We can't get any phone numbers. Try again...' error in Module 01/Lab 02 'Configure your environment for Teams Phone'

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#16] opened 2021-12-23 20:00 UTC
# Module: 01
## Lab/Demo: 02
Exercise 4
#### Step: 03

Description of issue

In Module 01/Lab 02/Exer 4/Task 4/Step 3 when attempting to click the '+Add' button in the 'Configure Caller ID Policies' section -  (or, also, trying check the existing config of either of the 2 preexisting 'SBAnon' or 'Global (Org-wide default)' entries) the config page will briefly appear, then return to the top-level 'Caller ID policies' page while displaying the error 'We can't get any phone numbers right now.  Try again...'

![image](https://user-images.githubusercontent.com/49700217/147286405-0ae47221-bb3c-4795-9f6c-188fc31a11a0.png)

Repro steps:

I'm currently running through a fresh QA test of this course (using the new ALH VMs from the Download center, standard Tenant) and have been experiencing this issue since yesterday morning Pacific Time once I got to that point.  

At first I thought it might have to do with MSFT backend resources just being somewhat slower/stressed over holiday rush, so I saved the lab and let it sit overnight - but upon resume this morning I am still experiencing it.  

I've gone back over all of the initial config in the previous exercises/tasks and as far as I can tell it is correct/no errors or typos - although I am going to go back and do yet another check for potential 'my mistakes' now.

I've done the standard clear cache/close all instances of Edge/login fresh (as either the expected Katie Jordan account, or as Mod Administrator) with no effect, in case it was some form of perms issue.

I'm not particularly savvy with this technology/functionality in Teams but given the phrasing of the error I wondered if it was simply that there are literally no Phone #s to be had - on the off chance it had any effect I briefly reset the 'Network region' of the Tacoma & Bellevue network sites to 'US', in place of 'UK' and let that sit for awhile...no effect.  (and have since changed it back, hopefully that 'freelancing' doesn't invalidate further use of this test run.)

I'm at a loss to explain this - is anyone who is far more experienced than me, ever seen this before and/or has any thoughts on potential issue to cause it?  (Do I take the error at face value - & it is  simply a phone #/backend resource depletion issue that may fix itself in a day/week or longer timeline if I am patient?)

**Comment by dahans-msft2** [comment] 2022-01-04 22:33
Acknowledged, investigating....

**Comment by dahans-msft2** [comment] 2022-01-07 22:49
Wasn't able to reproduce the issue and could have been service related or related to numbers available in the 206 area code.  I've updated instructions to suggest trying different area codes if that's the case, because there typically aren't any numbers in the 206 area.  Closing this for now, will update with PR #17 .

**Closed by dahans-msft2** 2022-01-07 22:49 UTC
